import requests
import streamlit as st
import subprocess
import time
import uuid
from urllib.parse import urlparse, parse_qs
from twelvelabs import TwelveLabs
from snowflake_connect import get_snowflake_connection
from google.generativeai import configure, GenerativeModel

# === API Keys ===
api_key = "tlk_1CPRENS1M7PJ1G2HTQ1QN2JHC2RS"
index_id = "67f69df0f42e97f625940bcd"
client = TwelveLabs(api_key=api_key)

configure(api_key="AIzaSyD5avNnryzA6Y-sDTRS_vcj55O91Xlcq5o") 
gemini_model = GenerativeModel("gemini-1.5-pro")

# === Session States ===
if 'processing' not in st.session_state:
    st.session_state.processing = False
if 'results' not in st.session_state:
    st.session_state.results = []
if 'chat_history' not in st.session_state:
    st.session_state.chat_history = {}
if 'current_video_id' not in st.session_state:
    st.session_state.current_video_id = None
if 'current_summary' not in st.session_state:
    st.session_state.current_summary = None

# === Core Functions ===
def get_video_id(url):
    parsed_url = urlparse(url)
    query = parse_qs(parsed_url.query)
    if 'v' in query:  # For YouTube URLs
        return query['v'][0]
    return parsed_url.path.split('/')[-1]  # For SharePoint or other links

def download_youtube_video(url, video_id):
    output_path = f"video_{video_id}.mp4"
    command = f"yt-dlp -f best -o {output_path} {url}"
    subprocess.run(command, shell=True, check=True)
    return output_path

def download_sharepoint_video(url, token):
    try:
        sharepoint_path = url.split("/personal/")[1]
        user_name, relative_path = sharepoint_path.split("/", 1)
        user_email = user_name.replace("_", ".").replace(".cginfinity.com", "@cginfinity.com")
        st.write(f"User Email: {user_email}")

        file_path = "/".join(relative_path.split("/")[1:])
        st.write(f"File Path: {file_path}")

        site_resp = requests.get(
            f"https://graph.microsoft.com/v1.0/users/{user_email}/drive/root",
            headers={"Authorization": f"Bearer {token}"}
        )

        if site_resp.status_code != 200:
            raise Exception(f"Failed to retrieve OneDrive site. Error: {site_resp.json()}")

        drive_id = site_resp.json().get("parentReference", {}).get("driveId")
        if not drive_id:
            raise Exception("Could not retrieve drive ID.")

        item_resp = requests.get(
            f"https://graph.microsoft.com/v1.0/drives/{drive_id}/root:/{file_path}",
            headers={"Authorization": f"Bearer {token}"}
        )

        if item_resp.status_code != 200:
            raise Exception(f"File not found. Error: {item_resp.json()}")

        item_id = item_resp.json().get("id")

        content_resp = requests.get(
            f"https://graph.microsoft.com/v1.0/drives/{drive_id}/items/{item_id}/content",
            headers={"Authorization": f"Bearer {token}"},
            stream=True
        )

        if content_resp.status_code == 200:
            output_path = "temp_video.mp4"
            with open(output_path, "wb") as f:
                for chunk in content_resp.iter_content(chunk_size=8192):
                    f.write(chunk)
            return output_path
        else:
            raise Exception(f"Download failed. Status: {content_resp.status_code}")
    except Exception as e:
        raise Exception(f"Error downloading SharePoint video: {str(e)}")

# === DATABASE FUNCTION - CORRECTED ===
def save_summary_to_database(video_id, summary):
    try:
        conn = get_snowflake_connection()
        cursor = conn.cursor()
        # Create table if not exists
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS VIDEO_SUMMARIES (
                VIDEO_ID STRING PRIMARY KEY,
                SUMMARY TEXT
            )
        """)
        # Insert or Update the record
        cursor.execute("""
            MERGE INTO VIDEO_SUMMARIES AS target
            USING (SELECT %s AS VIDEO_ID, %s AS SUMMARY) AS source
            ON target.VIDEO_ID = source.VIDEO_ID
            WHEN MATCHED THEN UPDATE SET SUMMARY = source.SUMMARY
            WHEN NOT MATCHED THEN INSERT (VIDEO_ID, SUMMARY) VALUES (source.VIDEO_ID, source.SUMMARY)
        """, (video_id, summary))
        conn.commit()
        cursor.close()
        conn.close()
        st.success("Summary saved to database successfully!")
    except Exception as e:
        st.error(f"Database Error: {str(e)}")

# === Example Usage after you generate summary ===
def process_summary_and_store(url):
    video_id = get_video_id(url)
    st.session_state.current_video_id = video_id

    # Assume we generate a summary here, hardcoding for example
    generated_summary = "This is a sample summary generated by AI."

    # Save summary to database
    save_summary_to_database(video_id, generated_summary)

    # Update session state
    st.session_state.current_summary = generated_summary
    st.success("Processing complete.")

# === Streamlit UI ===
st.title("Video Summarizer and ChatBot")

video_url = st.text_input("Enter YouTube or SharePoint Video URL:")

if st.button("Process Video"):
    if video_url:
        process_summary_and_store(video_url)
    else:
        st.warning("Please enter a valid URL!")
